#!/usr/bin/env bash
# scripts/set-env.sh — Configure the WS endpoint for native dev builds
#
# Usage:
#   ./scripts/set-env.sh --env prod          # Use current production pod URL
#   ./scripts/set-env.sh --env local         # ws://localhost:3000
#   ./scripts/set-env.sh --env android       # ws://10.0.2.2:3000  (Android emulator)
#   ./scripts/set-env.sh --env lan <IP>      # ws://<IP>:3000  (physical device on LAN)
#   ./scripts/set-env.sh --env preview <URL> # Custom preview pod URL
#   ./scripts/set-env.sh --env custom <URL>  # Fully custom wss://... URL
#
# Output: writes react-native/.env.local (gitignored)
# Web builds are NOT affected — they always auto-derive from window.location at runtime.

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(dirname "$SCRIPT_DIR")"
ENV_LOCAL="$REPO_ROOT/react-native/.env.local"

ENV_TYPE="${1#--env}"
ENV_TYPE="${ENV_TYPE# }"
EXTRA="${2:-}"

if [[ -z "$1" ]]; then
  echo "Usage: $0 --env <prod|local|android|lan <IP>|preview <URL>|custom <URL>>"
  exit 1
fi

# Shift past --env
shift

ENV_TYPE="${1}"
shift || true
EXTRA="${1:-}"

case "$ENV_TYPE" in
  prod)
    # Fetch from GitHub repo variable if gh CLI available
    if command -v gh &>/dev/null; then
      WS_URL=$(gh variable get TRIVIA_PROD_WS_URL --repo redsitesoftware/trivia-night-e2e 2>/dev/null || true)
    fi
    if [[ -z "$WS_URL" ]]; then
      echo "❌ Could not fetch TRIVIA_PROD_WS_URL from GitHub. Run: gh auth login"
      echo "   Or use: $0 --env custom wss://trivia-night-e2e-XXXXX.user-pods.alphinium.io"
      exit 1
    fi
    LABEL="production pod"
    ;;
  local)
    WS_URL="ws://localhost:3000"
    LABEL="local dev (localhost:3000)"
    ;;
  android)
    WS_URL="ws://10.0.2.2:3000"
    LABEL="Android emulator (10.0.2.2:3000)"
    ;;
  lan)
    if [[ -z "$EXTRA" ]]; then
      echo "❌ LAN mode requires an IP address: $0 --env lan 192.168.x.x"
      exit 1
    fi
    WS_URL="ws://${EXTRA}:3000"
    LABEL="LAN device ($EXTRA:3000)"
    ;;
  preview|custom)
    if [[ -z "$EXTRA" ]]; then
      echo "❌ $ENV_TYPE mode requires a URL: $0 --env $ENV_TYPE wss://..."
      exit 1
    fi
    WS_URL="$EXTRA"
    # Ensure wss:// or ws:// prefix
    if [[ ! "$WS_URL" =~ ^wss?:// ]]; then
      WS_URL="wss://$WS_URL"
    fi
    LABEL="$ENV_TYPE ($WS_URL)"
    ;;
  *)
    echo "❌ Unknown env type: $ENV_TYPE"
    echo "   Valid options: prod, local, android, lan, preview, custom"
    exit 1
    ;;
esac

# Write .env.local
cat > "$ENV_LOCAL" <<EOF
# Generated by scripts/set-env.sh on $(date)
# DO NOT COMMIT — this file is gitignored
# Env: $LABEL

EXPO_PUBLIC_WS_URL=$WS_URL
EOF

echo "✅ react-native/.env.local written"
echo "   EXPO_PUBLIC_WS_URL=$WS_URL"
echo ""
echo "   Restart Metro / expo start for changes to take effect."
echo "   Web builds are unaffected (they use window.location at runtime)."
